[tools]
elixir = "1.18"
erlang = "28.0"
node = "24.5"
python = "3.13"
rust = "1.85"
uv = "latest"

[settings]
experimental = true
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["python"]
